services:
  php-service:
    build:
      context: ./
    restart: unless-stopped
    init: true
    ports:
      - "9000:9000"
    networks:
      - app-network
    # env_file: ./.env  # Uncomment if .env file exists
  ts-service:
    build:
      context: ./components
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"
    networks:
      - app-network
    # env_file: ./components/.env  # Uncomment if .env file exists
networks:
  app-network:
    driver: bridge