services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zim-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - zim-network
    depends_on:
      - db
      - redis

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: zim-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - zim-network
    depends_on:
      - app

  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    container_name: zim-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zim-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: zim-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - zim-network

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zim-queue
    restart: unless-stopped
    command: php artisan queue:work
    volumes:
      - ./:/var/www/html
    networks:
      - zim-network
    depends_on:
      - app
      - db
      - redis

networks:
  zim-network:
    driver: bridge 